# 📊 Fundamentos de Pandas — Dia 1 (Fase 1: Python Básico)

**Data:** 2026-09-04
**Autor:** Gutemberg Rapôso
**Tópico:** Fundamentos de Pandas — criação, inspeção, seleção, filtragem e operações básicas em DataFrames

---

## O que é o Pandas?

O **Pandas** é a biblioteca mais importante para *análise e manipulação de dados* em Python.
Ela introduz duas estruturas de dados fundamentais:

- **`Series`**: um vetor unidimensional rotulado (como uma coluna).
- **`DataFrame`**: uma tabela bidimensional (linhas e colunas), semelhante a uma planilha
  do Excel ou a uma tabela de banco de dados.

### Por que o Pandas importa para Ciência de Dados?

Antes de treinar qualquer modelo de *machine learning*, precisamos **carregar, limpar,
explorar e transformar** os dados. Estima-se que cientistas de dados passem cerca de
**80% do tempo** nessa etapa de preparação — e o Pandas é a ferramenta central para isso.

> **Conexão com a minha área (Linguística):** assim como analisamos *corpora* linguísticos
> (grandes conjuntos de textos) para estudar padrões da língua, o Pandas nos permite tratar
> tabelas de dados como *corpora* estruturados, contando frequências, filtrando ocorrências
> e agregando informações — habilidades que se transferem diretamente para o
> **Processamento de Linguagem Natural (PLN)** aplicado à educação.

## 1. Importando as bibliotecas

Começamos importando o `pandas` (convencionalmente apelidado de `pd`), o `numpy`
(para operações numéricas) e o `seaborn` (que traz *datasets* públicos prontos para uso).

In [1]:
# Import core libraries for data manipulation and analysis
import pandas as pd
import numpy as np
import seaborn as sns

# Display all columns when printing DataFrames
pd.set_option("display.max_columns", None)

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("seaborn version:", sns.__version__)

pandas version: 2.2.3
numpy version: 1.26.4
seaborn version: 0.13.2

## 2. Criando DataFrames do zero

Existem várias formas de criar um `DataFrame`. As duas mais comuns são:

1. A partir de um **dicionário** (as chaves viram nomes de colunas).
2. A partir de uma **lista de dicionários** (cada dicionário vira uma linha).

In [2]:
# Method 1: create a DataFrame from a dictionary
# Each key becomes a column, each list becomes the column values
students = {
    "name": ["Ana", "Bruno", "Carla", "Diego"],
    "age": [23, 31, 27, 45],
    "city": ["Palmas", "Recife", "Palmas", "Salvador"],
}
df_students = pd.DataFrame(students)
df_students

    name  age      city
0    Ana   23    Palmas
1  Bruno   31    Recife
2  Carla   27    Palmas
3  Diego   45  Salvador

In [3]:
# Method 2: create a DataFrame from a list of dictionaries
# Each dictionary becomes a row
records = [
    {"name": "Elena", "age": 29, "city": "Fortaleza"},
    {"name": "Felipe", "age": 38, "city": "Palmas"},
]
df_records = pd.DataFrame(records)
df_records

     name  age       city
0   Elena   29  Fortaleza
1  Felipe   38     Palmas

## 3. Carregando datasets do seaborn (iris e tips)

O `seaborn` disponibiliza *datasets* públicos e reais, muito usados para aprendizado:

- **`iris`**: medidas de flores (comprimento/largura de sépalas e pétalas) de 3 espécies.
- **`tips`**: registros de gorjetas em um restaurante (valor da conta, gorjeta, dia, etc.).

Usamos `sns.load_dataset()` para carregá-los diretamente como `DataFrame`.

In [4]:
# Load two real public datasets bundled with seaborn
iris = sns.load_dataset("iris")
tips = sns.load_dataset("tips")

print("iris shape:", iris.shape)
print("tips shape:", tips.shape)

iris shape: (150, 5)
tips shape: (244, 7)

## 4. Inspeção básica dos dados

Antes de analisar, sempre inspecionamos o *dataset* para entender sua estrutura.
Os métodos e atributos mais usados são:

| Método/Atributo | O que faz |
|-----------------|-----------|
| `.shape`        | Retorna (nº de linhas, nº de colunas) |
| `.dtypes`       | Mostra o tipo de dado de cada coluna |
| `.head(n)`      | Exibe as primeiras `n` linhas (padrão 5) |
| `.tail(n)`      | Exibe as últimas `n` linhas |
| `.info()`       | Resumo: colunas, valores não-nulos e tipos |
| `.describe()`   | Estatísticas descritivas das colunas numéricas |

In [5]:
# .shape -> (rows, columns)
print("iris shape:", iris.shape)

# .dtypes -> data type of each column
print("\niris dtypes:")
print(iris.dtypes)

iris shape: (150, 5)

iris dtypes:
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [6]:
# .head() shows the first rows (default = 5)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# .tail() shows the last rows
iris.tail(3)

     sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [8]:
# .info() gives a concise technical summary of the DataFrame
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
# .describe() computes descriptive statistics for numeric columns
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## 5. Seleção de colunas

Podemos selecionar:

- **Uma coluna** → retorna uma `Series`: `df["coluna"]`
- **Múltiplas colunas** → retorna um `DataFrame`: `df[["col1", "col2"]]` (note a lista dupla `[[ ]]`)

In [10]:
# Select a single column -> returns a Series
species = iris["species"]
print(type(species))
species.head()

<class 'pandas.core.series.Series'>

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [11]:
# Select multiple columns -> returns a DataFrame (note the double brackets)
subset = iris[["sepal_length", "species"]]
subset.head()

   sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa

## 6. Filtragem de linhas com condições booleanas

Podemos filtrar linhas usando **condições booleanas**. A condição gera uma máscara
(uma `Series` de `True`/`False`) que seleciona apenas as linhas desejadas.

Para combinar condições use `&` (E), `|` (OU) e envolva cada condição em parênteses.

In [12]:
# Filter: only rows where species is "setosa"
setosa = iris[iris["species"] == "setosa"]
print("Number of setosa rows:", setosa.shape[0])
setosa.head()

Number of setosa rows: 50

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
# Combine multiple conditions with & (and) / | (or)
# Long-petaled virginica flowers
big_virginica = iris[(iris["species"] == "virginica") & (iris["petal_length"] > 6.0)]
big_virginica

     sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

## 7. Ordenação com `.sort_values()`

O método `.sort_values()` ordena o `DataFrame` por uma ou mais colunas.
Use `ascending=False` para ordem decrescente.

In [14]:
# Sort the tips dataset by total_bill in descending order
tips_sorted = tips.sort_values("total_bill", ascending=False)
tips_sorted.head()

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [15]:
# Sort by multiple columns: first by day, then by tip (descending)
tips.sort_values(["day", "tip"], ascending=[True, False]).head()

     total_bill   tip     sex smoker   day   time  size
141       34.30  6.70    Male     No  Thur  Lunch     6
88        24.71  5.85    Male     No  Thur  Lunch     2
85        34.83  5.17  Female     No  Thur  Lunch     4
83        32.68  5.00    Male    Yes  Thur  Lunch     2
142       41.19  5.00    Male     No  Thur  Lunch     5

## 8. Agregação básica com `.groupby()`

O `.groupby()` agrupa linhas que compartilham um valor em comum e permite calcular
estatísticas por grupo (média, contagem, soma, etc.). É a base da análise exploratória.

In [16]:
# Average tip per day of the week
avg_tip_by_day = tips.groupby("day", observed=True)["tip"].mean()
avg_tip_by_day

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [17]:
# Count number of records per species in the iris dataset
count_by_species = iris.groupby("species", observed=True)["sepal_length"].count()
count_by_species

species
setosa        50
versicolor    50
virginica     50
Name: sepal_length, dtype: int64

In [18]:
# Multiple aggregations at once with .agg()
tips.groupby("day", observed=True)["total_bill"].agg(["mean", "count", "max"])

           mean  count    max
day
Thur  17.682742     62  43.11
Fri   17.151579     19  40.17
Sat   20.441379     87  50.81
Sun   21.410000     76  48.17

## 9. Tratamento de valores ausentes (missing values)

Dados reais quase sempre têm valores ausentes (`NaN`). Os principais métodos são:

- `.isnull()` → indica quais células estão vazias (`True`/`False`).
- `.dropna()` → remove linhas (ou colunas) com valores ausentes.
- `.fillna(valor)` → preenche valores ausentes com um valor definido.

Vamos criar um pequeno `DataFrame` com valores ausentes para demonstrar.

In [19]:
# Create a small DataFrame with some missing values (np.nan)
data_missing = pd.DataFrame({
    "student": ["Ana", "Bruno", "Carla", "Diego"],
    "score": [8.5, np.nan, 7.0, np.nan],
    "hours_studied": [10, 5, np.nan, 8],
})
data_missing

  student  score  hours_studied
0     Ana    8.5           10.0
1   Bruno    NaN            5.0
2   Carla    7.0            NaN
3   Diego    NaN            8.0

In [20]:
# .isnull() shows which cells are missing; .sum() counts them per column
data_missing.isnull().sum()

student          0
score            2
hours_studied    1
dtype: int64

In [21]:
# .dropna() removes rows that contain any missing value
data_missing.dropna()

  student  score  hours_studied
0     Ana    8.5           10.0

In [22]:
# .fillna() fills missing values -- here we fill scores with the column mean
filled = data_missing.copy()
filled["score"] = filled["score"].fillna(filled["score"].mean())
filled["hours_studied"] = filled["hours_studied"].fillna(0)
filled

  student  score  hours_studied
0     Ana   8.50           10.0
1   Bruno   7.75            5.0
2   Carla   7.00            0.0
3   Diego   7.75            8.0

## 10. Aplicação à Linguística e ao Ensino de Inglês 🎓

Como venho da **Linguística/Sociolinguística** e tenho interesse em **PLN aplicado à educação**,
vou criar um pequeno `DataFrame` **pedagógico** com palavras do vocabulário de inglês e suas
frequências.

> ⚠️ **Nota:** os números abaixo são um **exemplo didático criado manualmente** apenas para
> ilustrar as operações do Pandas. **Não** representam dados reais de frequência de um *corpus*.
> Em projetos reais, essas contagens viriam de *corpora* como o COCA ou o BNC.

Esse tipo de tabela (palavra → frequência) é exatamente a estrutura usada em muitas tarefas de
PLN, como a construção de listas de vocabulário graduadas por nível para aprendizes de inglês.

In [23]:
# Pedagogical example (manually created for teaching purposes -- NOT real corpus data)
# A small vocabulary list with illustrative frequency counts and CEFR levels
vocab = pd.DataFrame({
    "word": ["the", "school", "teacher", "linguistics", "corpus", "morpheme"],
    "part_of_speech": ["article", "noun", "noun", "noun", "noun", "noun"],
    "frequency": [1200, 340, 180, 25, 12, 4],   # illustrative counts only
    "cefr_level": ["A1", "A1", "A2", "C1", "C2", "C2"],
})
vocab

          word part_of_speech  frequency cefr_level
0          the        article       1200         A1
1       school           noun        340         A1
2      teacher           noun        180         A2
3  linguistics           noun         25         C1
4       corpus           noun         12         C2
5     morpheme           noun          4         C2

In [24]:
# We can apply everything learned today to this vocabulary DataFrame:

# 1) Filter: advanced vocabulary (C1/C2 level)
advanced = vocab[vocab["cefr_level"].isin(["C1", "C2"])]
print("Advanced vocabulary (C1/C2):")
print(advanced[["word", "frequency"]].to_string(index=False))

# 2) Sort by frequency (most frequent first)
print("\nSorted by frequency:")
print(vocab.sort_values("frequency", ascending=False)[["word", "frequency"]].to_string(index=False))

Advanced vocabulary (C1/C2):
       word  frequency
linguistics         25
     corpus         12
   morpheme          4

Sorted by frequency:
       word  frequency
        the       1200
     school        340
    teacher        180
linguistics         25
     corpus         12
   morpheme          4

In [25]:
# 3) Aggregate: average frequency per CEFR level
avg_freq_by_level = vocab.groupby("cefr_level", observed=True)["frequency"].mean()
print("Average (illustrative) frequency per CEFR level:")
avg_freq_by_level

Average (illustrative) frequency per CEFR level:

cefr_level
A1    770.0
A2    180.0
C1     25.0
C2      8.0
Name: frequency, dtype: float64

## 11. Resumo do Dia 1 ✅

### O que aprendi hoje

- **O que é o Pandas** e por que ele é central em Ciência de Dados.
- **Criar DataFrames** a partir de dicionários e de listas de dicionários.
- **Carregar datasets reais** do seaborn (`iris` e `tips`).
- **Inspecionar dados** com `.shape`, `.dtypes`, `.head()`, `.tail()`, `.info()` e `.describe()`.
- **Selecionar colunas** (uma ou várias).
- **Filtrar linhas** com condições booleanas combinadas (`&`, `|`).
- **Ordenar** dados com `.sort_values()`.
- **Agregar** dados com `.groupby()` + `.mean()`, `.count()` e `.agg()`.
- **Tratar valores ausentes** com `.isnull()`, `.dropna()` e `.fillna()`.
- Apliquei tudo a um **exemplo de vocabulário de inglês**, conectando Pandas ao PLN e à educação.

### Próximos passos (Dia 2)

- Aprofundar a **Análise Exploratória de Dados (EDA)** na pasta `02_eda/`.
- Praticar **visualização de dados** com `matplotlib` e `seaborn`.
- Explorar `.merge()`, `.pivot_table()` e operações mais avançadas do Pandas.

---

*Portfólio de Ciência de Dados — jornada de Cientista de Dados Júnior → Sênior.*